### ISSUE TITLE
Implements NATS Key/Value store tasks

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-nats#46]
### Feature description

NATS support Key/Value thanks to its JetStream object storage support.

We should add tasks to support:
- Creating a bucket: `io.kestra.plugin.nats.kv.CreateBucket`
- Putting a key/value: `io.kestra.plugin.nats.kv.Put`
- Getting a key/value: `io.kestra.plugin.nats.kv.Get`
- Deleting a key/value: `io.kestra.plugin.nats.kv.Del`

Information on the K/V support is here: https://docs.nats.io/nats-concepts/jetstream/key-value-store/kv_walkthrough

Java examples are here: https://github.com/nats-io/nats.java/blob/main/src/examples/java/io/nats/examples/jetstream/NatsKeyValueFull.java

**Comment by anna-geller** [comment]
@loicmathieu @Ben8t can the issue be closed? seem the PR is merged

**Comment by loicmathieu** [comment]
Yes it has been implemented in https://github.com/kestra-io/plugin-nats/pull/47/files
